import type { Authority } from './types';

const USC = (section: string) =>
  `https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title26-section${section}&num=0&edition=prelim`;

/**
 * The research library. Entries are keyed by `id`; rules reference these keys
 * rather than restating amounts, so a citation can never drift away from the
 * logic that relies on it.
 *
 * `lastVerified` records the date the URL resolved and the quoted figures were
 * re-read against the source. Re-check before relying on any entry for a live
 * engagement.
 */
export const AUTHORITIES: Authority[] = [
  {
    id: 'rp-2024-40-rate-schedules',
    topic: 'Individual ordinary income rate schedules',
    taxYear: 2025,
    ruleDescription:
      'Sets the seven ordinary income rate brackets for 2025 by filing status. The 37% bracket begins at $751,600 of taxable income for married individuals filing jointly and $626,350 for unmarried individuals.',
    citation: 'Rev. Proc. 2024-40, § 3.01, Tables 1-4',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/pub/irs-drop/rp-24-40.pdf',
    lastVerified: '2026-08-24',
    category: 'individualIncome',
    kind: 'revenueProcedure',
    relatedForms: ['Form 1040'],
  },
  {
    id: 'pl-119-21-standard-deduction',
    topic: 'Standard deduction (2025 amounts)',
    taxYear: 2025,
    ruleDescription:
      'Public Law 119-21 raised the 2025 standard deduction to $31,500 for married individuals filing jointly, $23,625 for heads of household and $15,750 for single filers and married individuals filing separately, superseding the amounts originally published in Rev. Proc. 2024-40.',
    citation: 'P.L. 119-21, § 70102; IRC § 63(c)',
    governmentSource: 'U.S. Government Publishing Office',
    sourceUrl: 'https://www.govinfo.gov/content/pkg/PLAW-119publ21/pdf/PLAW-119publ21.pdf',
    lastVerified: '2026-08-24',
    category: 'deductions',
    kind: 'publicLaw',
    relatedForms: ['Form 1040'],
  },
  {
    id: 'rp-2024-40-capital-gains',
    topic: 'Preferential rates on long-term capital gain and qualified dividends',
    taxYear: 2025,
    ruleDescription:
      'For 2025 the 0% rate applies to adjusted net capital gain up to $96,700 of taxable income (married filing jointly) and $48,350 (single). The 15% rate runs to $600,050 and $533,400 respectively; gain above those amounts is taxed at 20%.',
    citation: 'Rev. Proc. 2024-40, § 3.03; IRC § 1(h)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/pub/irs-drop/rp-24-40.pdf',
    lastVerified: '2026-08-24',
    category: 'investmentIncome',
    kind: 'revenueProcedure',
    relatedForms: ['Schedule D (Form 1040)', 'Form 8949'],
  },
  {
    id: 'irs-tc409-capital-gains',
    topic: 'Holding period and character of capital gain',
    taxYear: 'all',
    ruleDescription:
      'Gain on a capital asset held more than one year is long-term and eligible for preferential rates; assets held one year or less produce short-term gain taxed at ordinary rates.',
    citation: 'IRS Topic No. 409; IRC § 1222',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/taxtopics/tc409',
    lastVerified: '2026-08-24',
    category: 'investmentIncome',
    kind: 'agencyGuidance',
    relatedForms: ['Form 8949', 'Schedule D (Form 1040)'],
  },
  {
    id: 'irc-1411-niit',
    topic: 'Net investment income tax',
    taxYear: 'all',
    ruleDescription:
      'A 3.8% tax applies to the lesser of net investment income or the excess of modified adjusted gross income over $250,000 (married filing jointly), $200,000 (single or head of household) or $125,000 (married filing separately). These thresholds are statutory and are not indexed for inflation.',
    citation: 'IRC § 1411(a)-(b)',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('1411'),
    lastVerified: '2026-08-24',
    category: 'investmentIncome',
    kind: 'statute',
    relatedForms: ['Form 8960'],
  },
  {
    id: 'irs-i8960-niit-computation',
    topic: 'Computing net investment income',
    taxYear: 2025,
    ruleDescription:
      'Net investment income generally includes interest, dividends, annuities, royalties, rents and net capital gain, less properly allocable deductions. Wages, self-employment income and distributions from qualified retirement plans are excluded.',
    citation: 'Instructions for Form 8960',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i8960',
    lastVerified: '2026-08-24',
    category: 'investmentIncome',
    kind: 'formInstructions',
    relatedForms: ['Form 8960'],
  },
  {
    id: 'irc-3101b-additional-medicare',
    topic: 'Additional Medicare tax',
    taxYear: 'all',
    ruleDescription:
      'An additional 0.9% Medicare tax applies to wages, compensation and self-employment income above $250,000 (married filing jointly), $200,000 (single) or $125,000 (married filing separately). Employers withhold once wages exceed $200,000 without regard to filing status.',
    citation: 'IRC § 3101(b)(2)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl:
      'https://www.irs.gov/businesses/small-businesses-self-employed/questions-and-answers-for-the-additional-medicare-tax',
    lastVerified: '2026-08-24',
    category: 'individualIncome',
    kind: 'agencyGuidance',
    relatedForms: ['Form 8959'],
  },
  {
    id: 'rp-2024-40-amt',
    topic: 'Alternative minimum tax exemption and phaseout',
    taxYear: 2025,
    ruleDescription:
      'The 2025 AMT exemption is $137,000 for joint returns and $88,100 for unmarried individuals. The exemption phases out beginning at $1,252,700 and $626,350 of alternative minimum taxable income respectively.',
    citation: 'Rev. Proc. 2024-40, §§ 2.11-2.12; IRC § 55(d)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/pub/irs-drop/rp-24-40.pdf',
    lastVerified: '2026-08-24',
    category: 'individualIncome',
    kind: 'revenueProcedure',
    relatedForms: ['Form 6251'],
  },
  {
    id: 'irs-i6251-amt-preferences',
    topic: 'Common AMT adjustments for high-income individuals',
    taxYear: 2025,
    ruleDescription:
      'State and local taxes, miscellaneous itemized deductions and the bargain element on exercise of incentive stock options are added back in computing alternative minimum taxable income.',
    citation: 'Instructions for Form 6251',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i6251',
    lastVerified: '2026-08-24',
    category: 'individualIncome',
    kind: 'formInstructions',
    relatedForms: ['Form 6251'],
  },
  {
    id: 'pl-119-21-salt-cap',
    topic: 'State and local tax deduction limitation',
    taxYear: 2025,
    ruleDescription:
      'For 2025 the itemized deduction for state and local taxes is capped at $40,000 ($20,000 for married individuals filing separately). The cap is reduced by 30% of modified adjusted gross income above $500,000 ($250,000 if married filing separately) but not below $10,000 ($5,000).',
    citation: 'P.L. 119-21, § 70120; IRC § 164(b)(6)',
    governmentSource: 'U.S. Government Publishing Office',
    sourceUrl: 'https://www.govinfo.gov/content/pkg/PLAW-119publ21/pdf/PLAW-119publ21.pdf',
    lastVerified: '2026-08-24',
    category: 'deductions',
    kind: 'publicLaw',
    relatedForms: ['Schedule A (Form 1040)'],
  },
  {
    id: 'irc-164-salt',
    topic: 'Deduction for taxes paid',
    taxYear: 'all',
    ruleDescription:
      'Section 164 allows an itemized deduction for state and local income, real property and personal property taxes, subject to the aggregate dollar limitation in § 164(b)(6).',
    citation: 'IRC § 164',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('164'),
    lastVerified: '2026-08-24',
    category: 'deductions',
    kind: 'statute',
    relatedForms: ['Schedule A (Form 1040)'],
  },
  {
    id: 'irc-170b-agi-limits',
    topic: 'Percentage limitations on charitable contributions',
    taxYear: 'all',
    ruleDescription:
      'Cash contributions to public charities are deductible up to 60% of the contribution base; gifts of long-term capital gain property to public charities are limited to 30%. Contributions to non-operating private foundations are limited to 30% (cash) and 20% (appreciated property). Excess amounts carry forward five years.',
    citation: 'IRC § 170(b)(1)',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('170'),
    lastVerified: '2026-08-24',
    category: 'deductions',
    kind: 'statute',
    relatedForms: ['Schedule A (Form 1040)', 'Form 8283'],
  },
  {
    id: 'irs-p526-charitable',
    topic: 'Substantiation of charitable contributions',
    taxYear: 2025,
    ruleDescription:
      'A contemporaneous written acknowledgment is required for any single contribution of $250 or more. Noncash contributions over $5,000 generally require a qualified appraisal and a completed Form 8283, Section B.',
    citation: 'Publication 526; IRC § 170(f)(8), (f)(11)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/publications/p526',
    lastVerified: '2026-08-24',
    category: 'deductions',
    kind: 'publication',
    relatedForms: ['Form 8283'],
  },
  {
    id: 'rp-2024-40-annual-gift-exclusion',
    topic: 'Annual exclusion for gifts',
    taxYear: 2025,
    ruleDescription:
      'For calendar year 2025 the first $19,000 of gifts of present interests to any one donee is excluded from taxable gifts. The exclusion for gifts to a spouse who is not a U.S. citizen is $190,000.',
    citation: 'Rev. Proc. 2024-40, § 2.43; IRC §§ 2503(b), 2523(i)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/pub/irs-drop/rp-24-40.pdf',
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'revenueProcedure',
    relatedForms: ['Form 709'],
  },
  {
    id: 'irc-2503-present-interest',
    topic: 'Present interest requirement for the annual exclusion',
    taxYear: 'all',
    ruleDescription:
      'The annual exclusion is available only for gifts of a present interest. A transfer in trust is a gift of a future interest unless the beneficiary holds a right of immediate enjoyment, such as a withdrawal power.',
    citation: 'IRC § 2503(b)',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('2503'),
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'statute',
    relatedForms: ['Form 709'],
  },
  {
    id: 'irs-i709-filing-requirement',
    topic: 'When Form 709 must be filed',
    taxYear: 2025,
    ruleDescription:
      'A donor must file Form 709 if gifts to any one donee exceed the annual exclusion, if any gift is of a future interest regardless of amount, if spouses elect to split gifts, or if the donor allocates generation-skipping transfer exemption. Filing a return does not by itself mean gift tax is payable; tax is due only after the lifetime basic exclusion amount has been fully used.',
    citation: 'Instructions for Form 709 (2025), "Who Must File"',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i709',
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'formInstructions',
    relatedForms: ['Form 709'],
  },
  {
    id: 'irc-2513-gift-splitting',
    topic: 'Gift splitting between spouses',
    taxYear: 'all',
    ruleDescription:
      'Spouses may elect to treat a gift made by either of them to a third party as made one-half by each. The election requires both spouses to consent and generally requires each to file Form 709.',
    citation: 'IRC § 2513; Instructions for Form 709',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i709',
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'formInstructions',
    relatedForms: ['Form 709'],
  },
  {
    id: 'rp-2024-40-basic-exclusion',
    topic: 'Basic exclusion amount',
    taxYear: 2025,
    ruleDescription:
      'The basic exclusion amount for decedents dying, and gifts made, in 2025 is $13,990,000. Taxable gifts reduce the amount available at death through the unified credit.',
    citation: 'Rev. Proc. 2024-40, § 2.41; IRC § 2010(c)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/pub/irs-drop/rp-24-40.pdf',
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'revenueProcedure',
    relatedForms: ['Form 709', 'Form 706'],
  },
  {
    id: 'irc-2010-unified-credit',
    topic: 'Unified credit against estate and gift tax',
    taxYear: 'all',
    ruleDescription:
      'A single unified credit offsets gift tax during life and estate tax at death. Exclusion used on lifetime gifts is not available again at death.',
    citation: 'IRC § 2010',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('2010'),
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'statute',
    relatedForms: ['Form 709', 'Form 706'],
  },
  {
    id: 'irc-2631-gst-exemption',
    topic: 'Generation-skipping transfer tax exemption',
    taxYear: 2025,
    ruleDescription:
      'Each individual has a GST exemption equal to the basic exclusion amount, $13,990,000 for 2025, which may be allocated to transfers that skip a generation. Allocation is reported on Form 709, Schedule D.',
    citation: 'IRC § 2631; Rev. Proc. 2024-40, § 2.41',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('2631'),
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'statute',
    relatedForms: ['Form 709'],
  },
  {
    id: 'irs-p551-carryover-basis',
    topic: 'Basis of property acquired by gift',
    taxYear: 2025,
    ruleDescription:
      'A donee generally takes the donor’s adjusted basis in gifted property. Unlike property acquired from a decedent, gifted property does not receive a basis adjustment to fair market value.',
    citation: 'Publication 551; IRC § 1015',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/publications/p551',
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'publication',
    relatedForms: ['Form 709'],
  },
  {
    id: 'irc-2523-marital-deduction',
    topic: 'Gifts to a spouse',
    taxYear: 'all',
    ruleDescription:
      'Gifts to a U.S. citizen spouse qualify for an unlimited marital deduction. Gifts to a non-citizen spouse do not; they are instead eligible for an inflation-adjusted annual exclusion under § 2523(i).',
    citation: 'IRC § 2523',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('2523'),
    lastVerified: '2026-08-24',
    category: 'wealthTransfer',
    kind: 'statute',
    relatedForms: ['Form 709'],
  },
  {
    id: 'rp-2024-40-estates-trusts',
    topic: 'Fiduciary income tax rate schedule',
    taxYear: 2025,
    ruleDescription:
      'For 2025, estates and trusts reach the 37% bracket at $15,650 of taxable income. The bracket thresholds are $3,150 (24%), $11,450 (35%) and $15,650 (37%).',
    citation: 'Rev. Proc. 2024-40, § 3.01, Table 5; IRC § 1(e)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/pub/irs-drop/rp-24-40.pdf',
    lastVerified: '2026-08-24',
    category: 'fiduciary',
    kind: 'revenueProcedure',
    relatedForms: ['Form 1041'],
  },
  {
    id: 'irs-i1041-filing-threshold',
    topic: 'Form 1041 filing requirement',
    taxYear: 2025,
    ruleDescription:
      'The fiduciary of a domestic trust must file Form 1041 if the trust has any taxable income for the year, gross income of $600 or more regardless of taxable income, or a beneficiary who is a nonresident alien.',
    citation: 'Instructions for Form 1041, "Who Must File"; IRC § 6012(a)(4)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i1041',
    lastVerified: '2026-08-24',
    category: 'fiduciary',
    kind: 'formInstructions',
    relatedForms: ['Form 1041'],
  },
  {
    id: 'irc-661-distribution-deduction',
    topic: 'Distribution deduction and distributable net income',
    taxYear: 'all',
    ruleDescription:
      'A trust deducts amounts of distributable net income distributed to beneficiaries, and the beneficiaries include those amounts in income. Income retained by the trust is taxed at the compressed fiduciary rates.',
    citation: 'IRC §§ 641, 651, 661, 662',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('641'),
    lastVerified: '2026-08-24',
    category: 'fiduciary',
    kind: 'statute',
    relatedForms: ['Form 1041', 'Schedule K-1 (Form 1041)'],
  },
  {
    id: 'irc-671-grantor-trust',
    topic: 'Grantor trust rules',
    taxYear: 'all',
    ruleDescription:
      'Where the grantor is treated as the owner of a portion of a trust, the items of income, deduction and credit attributable to that portion are reported on the grantor’s own return rather than taxed to the trust.',
    citation: 'IRC §§ 671-679',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('671'),
    lastVerified: '2026-08-24',
    category: 'fiduciary',
    kind: 'statute',
    relatedForms: ['Form 1041', 'Form 1040'],
  },
  {
    id: 'irs-i5227-charitable-remainder',
    topic: 'Charitable remainder trust reporting',
    taxYear: 2025,
    ruleDescription:
      'A charitable remainder trust is generally exempt from income tax and files Form 5227 rather than Form 1041. Distributions to the noncharitable beneficiary carry out income under the four-tier ordering rules of § 664(b).',
    citation: 'Instructions for Form 5227; IRC § 664',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i5227',
    lastVerified: '2026-08-24',
    category: 'fiduciary',
    kind: 'formInstructions',
    relatedForms: ['Form 5227', 'Schedule K-1 (Form 1041)'],
  },
  {
    id: 'irc-664-crt-tiers',
    topic: 'Character of charitable remainder trust distributions',
    taxYear: 'all',
    ruleDescription:
      'Amounts distributed by a charitable remainder trust are treated first as ordinary income, then capital gain, then other income, then corpus, to the extent of the trust\u2019s income of each class for the year and undistributed income of that class from prior years.',
    citation: 'IRC \u00a7 664(b)',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('664'),
    lastVerified: '2026-08-24',
    category: 'fiduciary',
    kind: 'statute',
    relatedForms: ['Form 5227', 'Schedule K-1 (Form 1041)'],
  },
  {
    id: 'irc-1411-trust-threshold',
    topic: 'Net investment income tax for trusts and estates',
    taxYear: 2025,
    ruleDescription:
      'A trust or estate pays the 3.8% tax on the lesser of undistributed net investment income or the excess of adjusted gross income over the dollar amount at which the highest fiduciary bracket begins, $15,650 for 2025.',
    citation: 'IRC § 1411(a)(2); Rev. Proc. 2024-40, § 3.01',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('1411'),
    lastVerified: '2026-08-24',
    category: 'fiduciary',
    kind: 'statute',
    relatedForms: ['Form 8960', 'Form 1041'],
  },
  {
    id: 'fincen-114-threshold',
    topic: 'FBAR filing threshold',
    taxYear: 'all',
    ruleDescription:
      'A U.S. person with a financial interest in or signature authority over foreign financial accounts must file FinCEN Form 114 if the aggregate value of those accounts exceeds $10,000 at any time during the calendar year. The test is applied to the aggregate of all accounts, not account by account.',
    citation: '31 C.F.R. § 1010.350; 31 U.S.C. § 5314',
    governmentSource: 'Electronic Code of Federal Regulations',
    sourceUrl: 'https://www.ecfr.gov/current/title-31/section-1010.350',
    lastVerified: '2026-08-24',
    category: 'international',
    kind: 'regulation',
    relatedForms: ['FinCEN Form 114'],
  },
  {
    id: 'irs-fbar-overview',
    topic: 'FBAR filing mechanics and deadline',
    taxYear: 2025,
    ruleDescription:
      'The FBAR is filed electronically with FinCEN through the BSA E-Filing System, separately from the income tax return. The due date is April 15 with an automatic extension to October 15.',
    citation: 'IRS, Report of Foreign Bank and Financial Accounts (FBAR)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl:
      'https://www.irs.gov/businesses/small-businesses-self-employed/report-of-foreign-bank-and-financial-accounts-fbar',
    lastVerified: '2026-08-24',
    category: 'international',
    kind: 'agencyGuidance',
    relatedForms: ['FinCEN Form 114'],
  },
  {
    id: 'form-8938-thresholds',
    topic: 'Form 8938 reporting thresholds',
    taxYear: 2025,
    ruleDescription:
      'A specified individual living in the United States must file Form 8938 if specified foreign financial assets exceed $50,000 on the last day of the year or $75,000 at any time ($100,000 / $150,000 if married filing jointly). Taxpayers living abroad use $200,000 / $300,000 and $400,000 / $600,000. Form 8938 does not replace the FBAR; both may be required for the same account.',
    citation: 'Instructions for Form 8938; IRC § 6038D',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i8938',
    lastVerified: '2026-08-24',
    category: 'international',
    kind: 'formInstructions',
    relatedForms: ['Form 8938'],
  },
  {
    id: 'irs-i5471-foreign-corporation',
    topic: 'Information return for foreign corporations',
    taxYear: 2025,
    ruleDescription:
      'U.S. persons who are officers, directors or shareholders of certain foreign corporations file Form 5471. Categories of filer turn on ownership levels, acquisitions and dispositions, and control.',
    citation: 'Instructions for Form 5471; IRC §§ 6038, 6046',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i5471',
    lastVerified: '2026-08-24',
    category: 'international',
    kind: 'formInstructions',
    relatedForms: ['Form 5471'],
  },
  {
    id: 'irs-i8621-pfic',
    topic: 'Passive foreign investment company reporting',
    taxYear: 2025,
    ruleDescription:
      'A U.S. person who is a direct or indirect shareholder of a PFIC generally files Form 8621. Non-U.S. pooled investment funds, including many foreign mutual funds, commonly meet the PFIC definition.',
    citation: 'Instructions for Form 8621; IRC §§ 1291-1298',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i8621',
    lastVerified: '2026-08-24',
    category: 'international',
    kind: 'formInstructions',
    relatedForms: ['Form 8621'],
  },
  {
    id: 'irs-i3520-foreign-trust-gift',
    topic: 'Foreign trusts and large gifts from foreign persons',
    taxYear: 2025,
    ruleDescription:
      'Form 3520 reports transactions with foreign trusts, receipt of certain foreign gifts and inheritances. The reporting threshold for gifts from a nonresident alien individual or foreign estate is more than $100,000 in aggregate during the year.',
    citation: 'Instructions for Form 3520; IRC § 6039F',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i3520',
    lastVerified: '2026-08-24',
    category: 'international',
    kind: 'formInstructions',
    relatedForms: ['Form 3520', 'Form 3520-A'],
  },
  {
    id: 'irs-i1116-foreign-tax-credit',
    topic: 'Foreign tax credit',
    taxYear: 2025,
    ruleDescription:
      'A credit is available for income taxes paid or accrued to a foreign country, computed separately by category of income and limited to the U.S. tax attributable to foreign source income.',
    citation: 'Instructions for Form 1116; IRC §§ 901, 904',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i1116',
    lastVerified: '2026-08-24',
    category: 'international',
    kind: 'formInstructions',
    relatedForms: ['Form 1116'],
  },
  {
    id: 'irs-p54-citizens-abroad',
    topic: 'U.S. citizens and resident aliens abroad',
    taxYear: 2025,
    ruleDescription:
      'U.S. citizens and resident aliens are taxed on worldwide income regardless of where they live. Residence abroad may affect the foreign earned income exclusion, the Form 8938 thresholds and the filing deadline.',
    citation: 'Publication 54',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/publications/p54',
    lastVerified: '2026-08-24',
    category: 'international',
    kind: 'publication',
    relatedForms: ['Form 2555', 'Form 1116'],
  },
  {
    id: 'rp-2024-40-199a',
    topic: 'Qualified business income deduction thresholds',
    taxYear: 2025,
    ruleDescription:
      'The 2025 § 199A threshold amount is $394,600 for joint returns and $197,300 for all other returns, with a phase-in range of $100,000 and $50,000 respectively. Above the range the wage and property limitations apply in full and specified service trades or businesses are excluded.',
    citation: 'Rev. Proc. 2024-40, § 2.27; IRC § 199A(e)(2)',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/pub/irs-drop/rp-24-40.pdf',
    lastVerified: '2026-08-24',
    category: 'individualIncome',
    kind: 'revenueProcedure',
    relatedForms: ['Form 8995', 'Form 8995-A'],
  },
  {
    id: 'irc-199a',
    topic: 'Deduction for qualified business income',
    taxYear: 'all',
    ruleDescription:
      'Section 199A allows a deduction of up to 20% of qualified business income from a domestic trade or business, subject to W-2 wage and qualified property limitations and to exclusion of specified service trades or businesses above the threshold.',
    citation: 'IRC § 199A',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('199A'),
    lastVerified: '2026-08-24',
    category: 'individualIncome',
    kind: 'statute',
    relatedForms: ['Form 8995', 'Form 8995-A'],
  },
  {
    id: 'irc-6654-safe-harbor',
    topic: 'Estimated tax underpayment safe harbor',
    taxYear: 'all',
    ruleDescription:
      'No addition to tax applies where payments equal 90% of the current year tax or 100% of the prior year tax. Where prior year adjusted gross income exceeded $150,000, the prior-year safe harbor is 110%.',
    citation: 'IRC § 6654(d)(1)',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('6654'),
    lastVerified: '2026-08-24',
    category: 'compliance',
    kind: 'statute',
    relatedForms: ['Form 1040-ES', 'Form 2210'],
  },
  {
    id: 'irs-p505-withholding',
    topic: 'Withholding and estimated tax',
    taxYear: 2025,
    ruleDescription:
      'Supplemental wages such as bonuses and equity vesting are generally withheld at a flat 22% up to $1,000,000 and 37% above that amount, which frequently under-withholds for taxpayers in the top bracket.',
    citation: 'Publication 505',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/publications/p505',
    lastVerified: '2026-08-24',
    category: 'compliance',
    kind: 'publication',
    relatedForms: ['Form 1040-ES', 'Form W-4'],
  },
  {
    id: 'irs-p550-investment-income',
    topic: 'Investment income and expenses',
    taxYear: 2025,
    ruleDescription:
      'Publication 550 covers the treatment of interest, dividends, wash sales, investment interest expense and the identification of qualified dividends eligible for preferential rates.',
    citation: 'Publication 550',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/publications/p550',
    lastVerified: '2026-08-24',
    category: 'investmentIncome',
    kind: 'publication',
    relatedForms: ['Schedule B (Form 1040)'],
  },
  {
    id: 'irc-1091-wash-sale',
    topic: 'Wash sale rule',
    taxYear: 'all',
    ruleDescription:
      'A loss on the sale of stock or securities is disallowed where substantially identical securities are acquired within 30 days before or after the sale. The disallowed loss is added to the basis of the replacement position.',
    citation: 'IRC § 1091',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('1091'),
    lastVerified: '2026-08-24',
    category: 'investmentIncome',
    kind: 'statute',
    relatedForms: ['Form 8949'],
  },
  {
    id: 'irc-1202-qsbs',
    topic: 'Qualified small business stock',
    taxYear: 'all',
    ruleDescription:
      'Section 1202 excludes a portion of gain on the sale of qualified small business stock held more than five years, subject to per-issuer limits and to the requirement that the issuer be an eligible C corporation at issuance.',
    citation: 'IRC § 1202',
    governmentSource: 'Office of the Law Revision Counsel, U.S. House of Representatives',
    sourceUrl: USC('1202'),
    lastVerified: '2026-08-24',
    category: 'investmentIncome',
    kind: 'statute',
    relatedForms: ['Form 8949', 'Schedule D (Form 1040)'],
  },
  {
    id: 'irs-i1040-general',
    topic: 'Form 1040 income reporting',
    taxYear: 2025,
    ruleDescription:
      'Form 1040 and its schedules aggregate wages, interest, dividends, capital gain, business income, rents, royalties and income from partnerships, S corporations, estates and trusts into total income and then adjusted gross income.',
    citation: 'Instructions for Form 1040',
    governmentSource: 'Internal Revenue Service',
    sourceUrl: 'https://www.irs.gov/instructions/i1040gi',
    lastVerified: '2026-08-24',
    category: 'individualIncome',
    kind: 'formInstructions',
    relatedForms: ['Form 1040', 'Schedule 1', 'Schedule B', 'Schedule D', 'Schedule E'],
  },
];

const BY_ID = new Map(AUTHORITIES.map((authority) => [authority.id, authority]));

export function getAuthority(id: string): Authority {
  const authority = BY_ID.get(id);
  if (!authority) {
    throw new Error(`Unknown authority id "${id}". Add it to src/lib/research/authorities.ts.`);
  }
  return authority;
}

export function getAuthorities(ids: readonly string[]): Authority[] {
  return ids.map(getAuthority);
}

export const AUTHORITY_CATEGORY_LABELS: Record<Authority['category'], string> = {
  individualIncome: 'Individual income',
  investmentIncome: 'Investment income',
  deductions: 'Deductions',
  wealthTransfer: 'Wealth transfer',
  fiduciary: 'Fiduciary',
  international: 'International',
  compliance: 'Compliance and procedure',
};

export const AUTHORITY_KIND_LABELS: Record<Authority['kind'], string> = {
  statute: 'Statute',
  regulation: 'Regulation',
  publicLaw: 'Public law',
  revenueProcedure: 'Revenue procedure',
  formInstructions: 'Form instructions',
  publication: 'IRS publication',
  agencyGuidance: 'Agency guidance',
};
